### ISSUE TITLE
Missing Elements of the UX v 3.11.0

### ISSUE THREAD

**Issue by cidothia** [OpenNingia/l5r-character-manager-3#326]
I am missing aspects of the user interface using this build.  Here are a few screenshots.

https://i.imgur.com/SVwgzP5.png
https://i.imgur.com/mhqIjbz.png

I am rather new to the game and haven't used L5rCM very much so it's really hard to use right now.

**Comment by OpenNingia** [comment]
wow I never saw that before. Where did you download the app from? 
Would you mind to try a later build?

Download it here:

https://ci.appveyor.com/project/OpenNingia/l5r-character-manager-3/build/job/90kacsd9s1cdui30/artifacts

**Comment by giengus** [comment]
Download, and installing now.  I have found out that it only happens when I launch the program via opening the saved file rather than through launching the app directly, then opening the character.

The new build did not fix the issue.  All of the UI is present when launched via the shortcut for the app, but if you launch the app through the character file, then the UI is missing a lot.
